language: php

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    - MOCK_SERVER_PORT=3000

before_install:
  - nohup composer run-script mock-server &

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer install --no-interaction

script:
  - composer run-script specs-ci
  - composer run-script examples-ci

matrix:
  fast_finish: true
